version: '3'
services:
    inventario-app:
        platform: linux/amd64
        build: .
        container_name: inventario-app-back
        volumes:
            - ../inventario-app-back-logs:/usr/src/app/api/config/server/logs