version: '3'
services: 
    db_:
        platform: linux/amd64
        image:  mysql:latest
        container_name: inventario
        ports: 
            - 13306:3306
        environment: 
            MYSQL_ROOT_PASSWORD: "mysql_inventario2021"
            MYSQL_DATABASE: "db_inventario"
            MYSQL_USER: "user_inventario"
            MYSQL_PASSWORD: "mysql_inventario2021_root"
        volumes: 
            - ./schemas_db:/var/lib/mysql:rw
       