version: '3'
services: 
    db_inventario:
        platform: linux/amd64
        build: .
        container_name: db_inventario
        ports: 
            - 23306:3306
        environment: 
            MYSQL_ROOT_PASSWORD: "mysql_inventario2021"
            MYSQL_DATABASE: "db_inventario"
            MYSQL_USER: "user_inventario"
            MYSQL_PASSWORD: "mysql_inventario2021_root"
        volumes: 
            - ./schemas:/var/lib/mysql:rw
        networks: 
            inventario_network:
                aliases: 
                    - inventario_network_host
volumes: 
    schemas: {}
networks: 
    inventario_network:
        name: inventario_net
        driver: bridge